services:
  - type: web
    name: wpbulk
    runtime: docker
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
    healthCheckPath: /login
